// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SmilesInsurance_api.Models;

namespace SmilesInsurance_api.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AMLOLetter> AMLOLetter { get; set; }
        public virtual DbSet<AMLOList> AMLOList { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=147.50.164.131;Initial Catalog=Genie;Persist Security Info=True;User ID=devdba;Password=-v300wfhxt");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AMLOLetter>(entity =>
            {
                entity.Property(e => e.AMLOLetterId).ValueGeneratedNever();
            });

            modelBuilder.Entity<AMLOList>(entity =>
            {
                entity.Property(e => e.AMLOListId).ValueGeneratedNever();

                entity.Property(e => e.IdCardNo).IsUnicode(false);

                entity.HasOne(d => d.AMLOLetter)
                    .WithMany(p => p.AMLOLists)
                    .HasForeignKey(d => d.AMLOLetterId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_AMLOList_AMLOLetter1");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}