// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmilesInsurance_api.Models
{
    [Table("AMLOList", Schema = "amlo")]
    public partial class AMLOList
    {
        [Key]
        public Guid AMLOListId { get; set; }
        public Guid AMLOLetterId { get; set; }
        [StringLength(20)]
        public string IdCardNo { get; set; }
        [StringLength(100)]
        public string PassportNo { get; set; }
        public DateTime? BirthDate { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        public string SearchText { get; set; }
        [StringLength(100)]
        public string FirstName_eng { get; set; }
        [StringLength(100)]
        public string LastName_eng { get; set; }
        public bool? IsBlacklist { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? UpdateByUserId { get; set; }

        [ForeignKey(nameof(AMLOLetterId))]
        [InverseProperty("AMLOLists")]
        public virtual AMLOLetter AMLOLetter { get; set; }
    }
}